server:
  port: 8081


user:
  id: 45
  name: gastby
  info: 人生自古谁无死，留取丹心照汗青；

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rfid?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: 962464yp
    type: com.alibaba.druid.pool.DruidDataSource
    # 为数据库连接池设置诸多参数
    initialSize: 5
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    filters: stat
#    driver-class-name: com.mysql.cj.jdbc.Driver
